### ISSUE TITLE
Getting issue while downloading autoitlibrary

### ISSUE THREAD

**Issue by dipakbachhav** [nokia/robotframework-autoitlibrary#1]
```
C:\Python27\Scripts>pip install robotframework-autoitlibrary
Collecting robotframework-autoitlibrary
  Using cached robotframework-autoitlibrary-1.1.zip
Installing collected packages: robotframework-autoitlibrary
  Running setup.py install for robotframework-autoitlibrary ... error
    Complete output from command c:\python27\python.exe -u -c "import setuptools
, tokenize;__file__='c:\\users\\duser\\appdata\\local\\temp\\pip-build-byc
f1b\\robotframework-autoitlibrary\\setup.py';f=getattr(tokenize, 'open', open)(_
_file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file
__, 'exec'))" install --record c:\users\duser\appdata\local\temp\pip-bzuai
8-record\install-record.txt --single-version-externally-managed --compile:
    %SYSTEMROOT%\system32\regsvr32.exe /S c:\python27\Lib\site-packages\AutoItLi
brary\lib\AutoItX3.dll
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\duser\appdata\local\temp\pip-build-bycf1b\robotframew
ork-autoitlibrary\setup.py", line 70, in <module>
        subprocess.check_call(cmd, shell=True)
      File "c:\python27\lib\subprocess.py", line 540, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '%SYSTEMROOT%\system32\regsvr32.exe /
S c:\python27\Lib\site-packages\AutoItLibrary\lib\AutoItX3.dll' returned non-zer
o exit status 5

    ----------------------------------------
Command "c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\
\users\\duser\\appdata\\local\\temp\\pip-build-bycf1b\\robotframework-auto
itlibrary\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().r
eplace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --
record c:\users\duser\appdata\local\temp\pip-bzuai8-record\install-record.
txt --single-version-externally-managed --compile" failed with error code 1 in c
:\users\duser\appdata\local\temp\pip-build-bycf1b\robotframework-autoitlib
rary\

C:\Python27\Scripts>
```

**Comment by lucyking** [comment]
@dipakbachhav there, your python is 64 bit ?

**Comment by dipakbachhav** [comment]
@lucyking : Yes it is 

```
C:\AutoItLibrary-1.1>python
Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
```

**Comment by lucyking** [comment]
@dipakbachhav you should install [pywin32](https://sourceforge.net/projects/pywin32/files/pywin32/Build%20221/) correctly first:  
```
Python 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AM
D64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import win32com
>>> print win32com.__path__
['C:\\Python27\\lib\\site-packages\\win32com', 'C:\\Python27\\lib\\site-packages\\win32comext']
```

then try using :
`pip install -U robotframework-autoitlibrary --no-cache-dir --pre` 
to install the lastest rf-autoit lib.

**Comment by dipakbachhav** [comment]
I tried above solution after installing pywin32. but still facing same issue.

```
`Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\dipak.bachhav>python
Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (
AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import win32com.client
>>> import win32com
>>> print win32com.__path__
['C:\\Python27\\lib\\site-packages\\win32com', 'C:\\Python27\\lib\\site-packages
\\win32comext']
>>>
`
```
**Error After running  pip install -U robotframework-autoitlibrary --no-cache-dir --pre** 
```
`Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Python27\Scripts>pip install -U robotframework-autoitlibrary --no-cache-dir -
-pre
Collecting robotframework-autoitlibrary
  Downloading robotframework-autoitlibrary-1.2.1.zip (701kB)
    100% |################################| 706kB 799kB/s
Installing collected packages: robotframework-autoitlibrary
  Running setup.py install for robotframework-autoitlibrary ... error
    Complete output from command c:\python27\python.exe -u -c "import setuptools
, tokenize;__file__='c:\\users\\duser\\appdata\\local\\temp\\pip-build-jgf
kuv\\robotframework-autoitlibrary\\setup.py';f=getattr(tokenize, 'open', open)(_
_file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file
__, 'exec'))" install --record c:\users\duser\appdata\local\temp\pip-dddao
i-record\install-record.txt --single-version-externally-managed --compile:
    Don't think we need to unregister the old one...
    %SYSTEMROOT%\system32\regsvr32.exe /S c:\python27\Lib\site-packages\AutoItLi
brary\lib\AutoItX3.dll
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\duser\appdata\local\temp\pip-build-jgfkuv\robotframew
ork-autoitlibrary\setup.py", line 74, in <module>
        subprocess.check_call(cmd, shell=True)
      File "c:\python27\lib\subprocess.py", line 540, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '%SYSTEMROOT%\system32\regsvr32.exe /
S c:\python27\Lib\site-packages\AutoItLibrary\lib\AutoItX3.dll' returned non-zer
o exit status 5

    ----------------------------------------
Command "c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\
\users\\duser\\appdata\\local\\temp\\pip-build-jgfkuv\\robotframework-auto
itlibrary\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().r
eplace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --
record c:\users\duser\appdata\local\temp\pip-dddaoi-record\install-record.
txt --single-version-externally-managed --compile" failed with error code 1 in c
:\users\duser\appdata\local\temp\pip-build-jgfkuv\robotframework-autoitlib
rary\

C:\Python27\Scripts>`
```

**Comment by lucyking** [comment]
@dipakbachhav  
I've enhance this lib's ability to detect platform architecture automatically. [#6e2636](https://github.com/lucyking/robotframework-autoitlibrary/commit/6e2636ccfbee5a5eeaa04d412cd070cde2d97c65#diff-2eeaed663bd0d25b7e608891384b7298R64)  
Have you run ```pip install -U robotframework-autoitlibrary --no-cache-dir --pre```  to update?
...................................
**updating:**
there, I've see your updating. I'll inspect it this weekend  : )

**Comment by dipakbachhav** [comment]
Hi @lucyking : Yes Sir.. I ran same command. Kindly find ***Error After running pip install -U robotframework-autoitlibrary --no-cache-dir --pre*** Section from above comment

**Comment by lucyking** [comment]
yes, I've got it.  I'will try to set up an env to reproduce this issue this weekend. 
So sorry that I was at work during the daytime,  please be patinet.

**Comment by dipakbachhav** [comment]
Hi @lucyking ,

Did you find any solution? I am waiting for your solution.

Regards,
Dipak

**Comment by mihaiparvu** [comment]
You can bypass this error by running the command in an elevated command prompt. It requires admin privileges as it tries to inject some DLLs and ActiveX controls into the Windows Registry.

**Comment by vachirakorn** [comment]
> You can bypass this error by running the command in an elevated command prompt. It requires admin privileges as it tries to inject some DLLs and ActiveX controls into the Windows Registry.

works !
